
imxdrm-objs := imx-drm-core.o imx-fb.o

obj-$(CONFIG_DRM_IMX) += imxdrm.o

obj-$(CONFIG_DRM_IMX_PARALLEL_DISPLAY) += imx-parallel-display.o
obj-$(CONFIG_DRM_IMX_LCDC) += imx-lcdc-crtc.o
obj-$(CONFIG_DRM_IMX_FB_HELPER) += imx-fbdev.o
